import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { MantineProvider } from "@mantine/core";

 const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});
const theme ={
  fontFamily: poppins.className,
}

export const metadata: Metadata = {
  title: "Evently",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={poppins.className}>
          <MantineProvider theme={{
            fontFamily: poppins.className,
          }}>
            <div className="flex flex-col h-screen  ">
              <Header />
              <main className="flex-1">{children}</main>
              <Footer />
            </div>
          </MantineProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
